title: Planet openSUSE
email: admin@opensuse.org
description: >-
  Planet openSUSE site providing newest news from the openSUSE Project
baseurl: ""
url: "https://planet.opensuse.org"

markdown: kramdown
plugins:
  - jekyll-paginate-v2

autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    enabled: false
  tags:
    layouts:
      - 'language.html'
    title: ':tag'
    permalink: '/:tag'

pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  sort_reverse: true
  sort_field: 'created_at'
  trail:
    before: 2
    after: 2

exclude: [README.md, Gemfile, Gemfile.lock, planet.ini, planet.db, LICENSE, vendor, tests, bin, Rakefile]
