version: 2.1 

orbs:
  ruby: circleci/ruby@0.1.2 # Ruby orb registry: https://circleci.com/orbs/registry/orb/circleci/ruby

jobs: 
  build: 
    docker: 
      - image: circleci/ruby:2.6.3-stretch-node
    steps: 
      - checkout
      - ruby/bundle-install
      - run: 
          name: Build Pluto Jekyll
          command: bundler exec rake build
      - run: 
          name: Build Jekyll Website
          command: bundler exec jekyll build --trace
